#!/usr/bin/env bash
# Bash Script that creates and deletes files/ while handling signals


# Displays "I hate the kill command" when receiving a SIGTERM signal
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" TERM

# Displays "Y U no love me?!" when receiving a SIGINT signal
trap "echo 'Y U no love me?!'" INT

# terminates itself when receiving a SIGQUIT or SIGTERM
trap "rm /var/run/myscript.pid; exit" QUIT

# creates the file /var/run/myscript.pid containing its PID
echo "$$">/var/run/myscript.pid

# Displays "To infinity and beyond" indefinitely
while true
do
	echo "To infinity and beyond"
	sleep 2
done
