#!/usr/bin/env bash
# indefinitely: "To infinity and beyond". "I am invincible!!!" when receiving SIGTERM signal

trap  'echo "I am invincible!!!"' TERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
