#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Fizz for multiples of 3, Buzz for multiples of 5, FizzBuzz for multiples of both

for ((i=1; i<=100; i++))
do
	if ((i % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	else
		echo $i
	fi
done
