#!/usr/bin/env bash
# Display Best School 8 times, good luck ones, bad luck one, obeying chinese numerology

i=1
while [ $i -le 10 ]
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
